# Generated by Django 4.1.5 on 2023-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walkings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkings',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='walkings',
            name='date',
            field=models.DateField(verbose_name='Date of walkings'),
        ),
    ]
