# Generated by Django 4.1.5 on 2023-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='clothings',
            field=models.ManyToManyField(to='main_app.clothes'),
        ),
    ]
