# Generated by Django 4.1.5 on 2023-01-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_puppy_clothings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puppy',
            old_name='clothings',
            new_name='clothing',
        ),
    ]
